### ISSUE TITLE
Where did you start reverse engineering?

### ISSUE THREAD

**Issue by ciearius** [01F0/flashforge-finder-dashboard#1]
Hello, I'd like to see, if I could add some more features. Can you please provide some information on where to start? Did you reverse engineer the firmware or flash print (or maybe even something other than those two)?

**Comment by 01F0** [comment]
Hey :) 

I only traced the traffic sent to/from the printer.

You can use Wireshark to capture data on the printer port (8899 I think). 

Set up a Wireshark filter for the port, then connect to the printer in Flashprint and you should see data being captured.

Right-click those rows in Wireshark and then **Follow -> TCP Stream** and you will see the TCP data.

**Comment by ciearius** [comment]
Greetings 01F0,
Just after asking this question I found a post in a Google Group, saying there was some documentation! 
Apparently you can send some gcode commands via network.

Here is the post and the document it referred to: 
Post:
https://groups.google.com/forum/#!topic/flashforge/8A7TinFnDMQ
Document:
https://docs.google.com/viewer?a=v&pid=forums&srcid=MDcxMjQwNjcyMTkyNjQ3NTc3MTABMTc3Mzg5OTE2NTQ1ODM2MzU3MzgBcm5sZzNOY3kzRVlKATAuMQEBdjI&authuser=0

I've tried some of those commands on my Adventurer 3 (they match with what you found out).
Some of them are working... Some not yet. 
(FYI: writing my own API in nodejs)

Keep me posted on what you find in the doc!
